In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time

## Numpy vs. Torch

In [2]:
n = np.linspace(0, 1, 5)
t = torch.linspace(0, 1, 5)

In [5]:
n

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [9]:
n = np.arange(48).reshape(3,4,4)
t = torch.arange(48).reshape(3,4,4)

In [11]:
n

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [13]:
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]])

## Broadcasting Rules

In [16]:
a = np.ones((6,5))
b = np.arange(5).reshape((1,5))

In [17]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
b

array([[0, 1, 2, 3, 4]])

In [15]:
a+b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [20]:
a = torch.ones((6,5))
b = torch.arange(5).reshape((1,5))

In [21]:
a+b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

In [22]:
Image = torch.randn((256, 256, 3))
Scale = torch.tensor([0.5, 1.5, 1])

In [24]:
Result = Image*Scale
Result

tensor([[[-0.0116,  2.8878,  0.5161],
         [-0.0058,  0.8455,  1.6469],
         [ 0.4209, -2.0178, -1.1222],
         ...,
         [ 0.2095,  1.6486, -0.3434],
         [ 0.6038,  0.0735, -0.5222],
         [ 0.0949,  1.4364, -1.6197]],

        [[ 0.1346, -2.8148, -1.3719],
         [ 0.1537,  0.2825,  0.5833],
         [-0.0129, -1.4925, -0.0302],
         ...,
         [ 0.2715,  2.2777,  1.3745],
         [ 0.0501, -0.1268, -1.2639],
         [-0.0729, -0.1458, -1.9891]],

        [[-0.7795,  0.8754, -0.0721],
         [-0.4125,  2.0751, -0.6730],
         [-0.0149, -0.4938,  0.1945],
         ...,
         [-0.1020,  1.3631, -0.7928],
         [ 0.3687, -1.0977,  1.0162],
         [-1.1105,  2.6920,  0.9994]],

        ...,

        [[ 0.5973,  1.2185,  1.0693],
         [ 0.3607,  0.3135,  0.3813],
         [-0.0952,  2.5006, -0.3416],
         ...,
         [-0.2546, -0.9054,  1.4237],
         [-0.4242, -1.0454, -0.7141],
         [ 0.2552,  0.5269, -0.6070]],

        [[

In [25]:
Images = torch.randn((2, 256, 256, 3))
Scales = torch.tensor([0.5, 1.5, 1, 1.5, 1, 0.5]).reshape((2, 1, 1, 3))

In [26]:
Results = Images*Scales
Results

tensor([[[[-1.0698, -1.0983,  0.6905],
          [-0.2892, -0.5351,  0.6984],
          [ 0.1825, -0.9775,  0.8060],
          ...,
          [-0.6900, -1.6356,  1.4110],
          [ 0.1887, -2.1827,  1.0752],
          [-0.0594, -0.4214, -0.8355]],

         [[ 0.9300,  0.1335,  0.9396],
          [-0.3079, -2.7489, -1.0590],
          [ 0.3366, -0.2106,  1.2782],
          ...,
          [-0.3371,  1.7786, -0.4677],
          [ 0.0147, -0.2806,  0.9291],
          [ 0.4620, -0.5175, -0.3288]],

         [[-0.1316, -0.3055, -0.7113],
          [-0.6695,  1.0207,  0.0144],
          [ 1.1963, -0.1317,  0.7860],
          ...,
          [ 0.5748, -0.9786,  1.0853],
          [-1.2683,  3.7899,  0.9809],
          [ 0.0922,  2.7166,  1.1927]],

         ...,

         [[ 0.2185,  0.0484,  0.1205],
          [-0.3889,  2.4057, -0.0870],
          [ 0.2975,  1.2481,  0.2080],
          ...,
          [ 0.8303, -1.1227,  0.3973],
          [-0.7534,  1.2744,  0.2783],
          [-0.1980, -1

## Operations Across Dimensions

In [27]:
t = torch.tensor([0.5, 1, 3, 4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

In [33]:
t = torch.arange(20, dtype=float).reshape(5,4)
t, torch.mean(t, axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64))

In [34]:
t = torch.randn(5, 256, 256, 3)

In [37]:
torch.mean(t, axis=0).shape

torch.Size([256, 256, 3])

In [38]:
torch.mean(t, axis = -1).shape

torch.Size([5, 256, 256])

In [39]:
values, indices = torch.max(t, axis=-1)

In [41]:
indices

tensor([[[1, 1, 1,  ..., 0, 0, 0],
         [0, 1, 2,  ..., 2, 2, 2],
         [1, 1, 2,  ..., 0, 0, 0],
         ...,
         [1, 2, 0,  ..., 1, 1, 0],
         [0, 2, 0,  ..., 1, 2, 2],
         [1, 1, 1,  ..., 0, 0, 2]],

        [[0, 0, 2,  ..., 2, 2, 2],
         [1, 2, 1,  ..., 1, 2, 2],
         [2, 1, 1,  ..., 2, 0, 0],
         ...,
         [0, 1, 0,  ..., 1, 2, 0],
         [0, 1, 1,  ..., 0, 2, 2],
         [2, 0, 2,  ..., 0, 2, 1]],

        [[1, 2, 1,  ..., 2, 2, 0],
         [1, 2, 0,  ..., 2, 1, 0],
         [2, 1, 0,  ..., 1, 2, 1],
         ...,
         [0, 2, 1,  ..., 2, 0, 1],
         [1, 1, 2,  ..., 1, 1, 0],
         [2, 1, 2,  ..., 2, 1, 0]],

        [[0, 0, 1,  ..., 2, 2, 1],
         [0, 1, 0,  ..., 1, 2, 0],
         [0, 1, 1,  ..., 2, 1, 0],
         ...,
         [2, 2, 2,  ..., 0, 2, 2],
         [2, 0, 0,  ..., 2, 1, 0],
         [0, 0, 0,  ..., 1, 2, 0]],

        [[2, 2, 2,  ..., 2, 1, 2],
         [2, 0, 2,  ..., 0, 0, 1],
         [0, 2, 1,  ..., 2

## Differences between Pytorch and Numpy

In [45]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)
y = x.pow(3).sum()
y

tensor(917., grad_fn=<SumBackward0>)

In [46]:
y.backward()
x.grad

tensor([[ 75., 192.],
        [ 48., 108.]])

In [48]:
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)

## Matrix Multiplication

In [50]:
A = torch.randn((1000,1000))
B = torch.randn((1000,1000))

In [51]:
t1 = time.perf_counter()
torch.matmul(A,B)
t2 = time.perf_counter()
print(t2-t1)

0.006268362980335951


In [52]:
A = np.random.randn(int(1e6)).reshape((1000,1000))
B = np.random.randn(int(1e6)).reshape((1000,1000))

In [53]:
t1 = time.perf_counter()
A@B
t2 = time.perf_counter()
print(t2-t1)

0.01209839602233842
